changelog.md
package.json
readme.md

This commit makes preparations for future releases:
- A few small but useful NPM scripts are added to automate and validate
the release process.
- Documentation is provided to describe the process.
- A skeletal changelog is made. This is a reminder that the repo is
semantically versioned and published, and that releases must be
documented.

[build] Add NPM version scripts

---

package.json
readme.md

This change represents a good faith edit to apply the renaming guidance
decided in T253357:
- Rename readme title from "@wikimedia/mw-vue-components" to the exact
name voted on: "Wikimedia Vue UI". The package name could also be used
if that's preferred.
- Rename package and repo references to the ambiguous `@wikimedia/wvui`.
Package and repo names cannot contain spaces as far as I know and WVUI
was mentioned in the official rubric as an abbreviation.
Please also note:
- Repository naming itself will happen only after this patch has been
merged since there's no review process for that.
- Gerrit vs GitHub changes are out of scope.
- No other changes please. There are ~30 people involved just for
naming.
Bug: T253357

[build] rename to Wikimedia Vue UI

---

changelog.md
readme.md

Add BEM for the initial Less naming conventions. The convention may
change dramatically based on the outcome of T255100 but is at least the
interim convention to use until told otherwise.
The link is HTTP because there is no HTTPS site.
Bug: T255100

[docs] add initial Less naming conventions

---

.gitignore

The bundlesize report is automatically generated and should not be
versioned. Add it to .gitignore.

[dev] ignore bundlesize report

---

.storybook/preview.js
changelog.md

Disable the build type notification for Storybook documentation. This
library requires Vue.js as a peer dependency but does not ship it. The
Storybook documentation _does_ bundle Vue.js but it's probably better to
offer the development build even in production.

[dev] Suppress Vue.js Storybook build type reminder

---

.jest/jest.config.json
changelog.md

- Disable Babel. This was printing a warning when the cache was
invalidated: `npm -s run test:unit -- --no-cache`:
[vue-jest]: no .babelrc found, skipping babel compilation
- Don't report coverage for TypeScript definitions. These are not
executable.

[dev] Improve Jest configuration

---

changelog.md
package-lock.json
package.json
src/components/button/Button.snap.ts
src/components/button/Button.vue

Add the wikimedia-ui-base library. This is a needed dependency for all
or most Less variables as noted in the [OOUI migration guide].
An demo usage is included in wvui-button. This usage will be revised
properly when the real styles are added.
[OOUI migration guide]: https://www.mediawiki.org/wiki/Vue.js/OOUI_migration_guide
Bug: T256038

[dev][build][Less] add wikimedia-ui-base

---

.gitignore
.storybook/preview.js
changelog.md
readme.md

- Add viewport breakpoints from wikimedia-ui-base to Storybook. Also add
black and dark backgrounds.
- Simplify .gitignore's automatic generated documentation. Assume the
whole directory until otherwise is needed.
- Miscellaneous documentation improvements.

[dev] Add Storybook viewports

---

.prettierignore
changelog.md
package.json
readme.md

T256693 added a Prettier configuration file to Wikimediafy the
formatting. Unfortunately, some tooling assumes that if a Prettier
configuration is present, it applies to all files. Since we currently
only use Prettier for JSON and Markdown, this means it incorrectly runs
on everything else. This patch updates the Prettier ignores to exclude
those files.

[dev] Disable Prettier for everything except JSON and Markdown files

---

.eslintrc.json
.storybook/main.js
changelog.md
readme.md
tsconfig.json
webpack.config.js

eslint-plugin-jsdoc has a TypeScript mode. Enable it. Unfortunately, it
doesn't seem to work properly at the moment so disable a couple rules it
says it's supposed to that are causing errors. A similar approach was
taken recently [in the Popups repo] by one of the linter maintainers.
Also, fix the typing in the Storybook and Webpack configs. These aren't
currently being evaluated by the type checker as Webpack shakes them
out as non-functional. However, they can now be tested manually with
`npx tsc --noEmit --incremental false`. The readme has been revised.
[in the Popups repo]: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/Popups/+/536470c01d5bc1e798d9790f2df5645736b8ddcd%5E%21/#F0

[dev] Improve ESLint TypeScript config and fix JS config typing

---

.jest/jest.config.json
changelog.md

Styles are intentionally ignored in the Jest transformers but there is
experimental support available for Sass WVUI doesn't use. This was
printing a warning when the cache was invalidated,
`npm -s run test:unit -- --no-cache`:
[vue-jest]: Less and PostCSS are not currently compiled by vue-jest
Disable the warning.
https://github.com/vuejs/vue-jest/blob/1a6836a/README.md#css-options

[dev] Suppress superfluous Jest style warning

---

changelog.md
src/themes/wikimedia-ui.less

All incoming component patches (https://github.com/wikimedia/wvui/pull/46, https://github.com/wikimedia/wvui/pull/47) use the same less theme that imports `wikimedia-ui-base.less` and adds some variables to be used for styling components. I've decided to put it to separate patch so that it can be used widely.

[dev] Add wikimedia-ui theme

---

changelog.md
package.json
readme.md

Decouple versioning from publishing to allow arguments to be passed to
`npm publish`. This is needed to allow pushing the `@next` NPM tag via
`--tag next`.
I've tried to test out the documented procedures locally in a dummy repo
but it's possible I might need to give it another few iterations once
this is merged.

[build][dev] Enable development releases

---

package.json
readme.md

- Don't assume a branch when publishing. This breaks the rolling
development release workflow. Instead, push a branch only if it exists
and continue to assume any NPM artifact published has a tag.
- Add `--access public` to publish examples. `--access private` is the
default for scoped packages like `@wikimedia/*`.

[dev][build] fix NPM publishing

---

.eslintignore
.storybook/main.js
changelog.md
package.json
readme.md
tsconfig.json
webpack.config.js

Generate TypeScript definitions when building and add them to the NPM
package. These are needed by library consumers using type checking.
There was a broken lint in the readme on master this patch also fixes.

[build][fix] Export TypeScript definitions

---

.stylelintignore
bin/node-test-version
bin/release-dev
changelog.md
readme.md

I keep having to copy and paste these commands from the readme. I wanted
to put them in an NPM script but then I lose all the documentation.
Although I think we should avoid lengthy shell scripts if at all
possible, I think it's worth it in this case for the docs. I also
considered using JavaScript here but all the commands I want to run are
shell.

[build][dev] Move docs to development release script

---

changelog.md
package.json

The CSS and types were not being published in the NPM package, only the
main JavaScript. Publish all of dist except .eslintrc.json.

[build][fix] Publish bundled CSS and types

---

src/themes/wikimedia-ui.less

`border-radius-base` is `2px` and part of WikimediaUI Base.

Remove `border-radius-base` override

---

changelog.md
package.json

Development releases are reproducible by passing the timestamp to the
build script. Ideally, we'd keep publishing these tags so they could be
built directly from the commit. However, this is creating a lot of noise
and is unusual. Limit tag publishing to only alpha / beta / release
candidate and final releases.

[build][fix] Don't push tags for development releases

---

src/components/input/Input.vue

This patch fixes a Less `transition` lint. I adjusted the linter config
in the Button styles patch but apparently _never_ tested it. This patch
moves the Input transition to appear on one line just like in Button.

[dev] Fix transition lint

---

readme.md
src/entries/wvui.ts

Export version as the default prevents passing the entire library to the
components of the Vue instance. Move it to a named export instead.

[build][fix] Expose version as a named export

---

bin/release-dev
bin/release-pre
bin/release-prod
changelog.md
readme.md

Like the rolling development releases, the pre-release and production
releases require executing a number of shell commands that are easily
botched and don't fit into an NPM script. Add new scripts to automate
where possible.

[build][dev] Add production and pre-release scripts

---

webpack.config.js

[docs][dev] Correct small typo in vue-loader comment

---

changelog.md
package.json
readme.md

Renaming test files caused Jest to get confused.
Running this new scripts clears the Jest cache, which resolves this confusion.
[1] https://remarkablemark.org/blog/2018/11/21/jest-clear-cache/
[2] https://github.com/facebook/jest/issues/3705

Add npm script to clear Jest cache

---

src/components/button/Button.vue
src/themes/wikimedia-ui.less

Using `px` values is recommended and sufficient for
`min-width` and `min-height`.

[styles][button] Use WikimediaUI Base `min-width` and `min-height`

---

readme.md

Vue itself is not needed directly in this example.

[docs] Remove unused import in example integration

---

package-lock.json
package.json
src/components/input/Input.vue
src/themes/wikimedia-ui.less

Updating to v0.17.0, removing all variables that are now part of
the Base variables. Also amending `@line-height-component` to 20px
equivalent as `@padding-vertical-base` has been changed upstream to
provide undoubted support of high letter box scripts like Burmese.

[build][styles] Update WikimediaUI Base to latest and amend `@line-height-component`

---

.eslintrc.json

These are already inherited from wikimedia/language/* configs.

eslint: Remove ecmaVersion properites

---

package-lock.json

Use NVM's version of Node.js to install dependencies. Validated with
`npm ci`.

[fix][build] package-lock.json version

---

src/components/typeahead-search/http/SearchClient.ts
src/components/typeahead-search/http/restSearchClient.ts
src/http/fetch.notAvailable.test.ts
src/http/fetch.test.ts
src/http/fetch.ts

Combine fetch() and json() so it can be easily replaced by another implementation, like jQuery.ajax().
Add optional parameter to the SearchClient so a client can pass in an alternative getJson() implementation.
If none is provided then native fetch is used.

Combine fetch() and json()
